name: modu_3_dart_study
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
